from __future__ import annotations


EXAMPLE_BASE_VERSION = "9.9.9"
EXAMPLE_RELEASE_REF = f"release/v{EXAMPLE_BASE_VERSION}"
EXAMPLE_STABLE_TAG = f"v{EXAMPLE_BASE_VERSION}"
EXAMPLE_RC_TAG = f"{EXAMPLE_STABLE_TAG}-rc.1"
